sudo: false
language: python
python: 3.6

env:
  - TEST_WITH_CYTHON=true
  - TEST_WITH_CYTHON=false

install:
  - python -m pip install -r dev-requirements.txt

script:
  - pytest tests/ -vv --cov mashpack

after_script:
  - coverage -m

after_success:
  - codecov

notifications:
  email: false
